version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres-db
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 100
